---
title: "Andre Presentasjon"
author: "Gard Olav Dietrichson"
date: '`r format(Sys.time(), "%d-%m-%Y")`'
output: 
  beamer_presentation:
    theme: "AnnArbor"
    colortheme: "seahorse"
    fonttheme: "serif"
---
## Velkommen igjen!

## Plan for i dag

- Bli *enda mer* kjent
- Seminaropplegget fremover
  - Obligatoriske Krav
  - Kvalifiseringsoppgaver
  - Forventninger
- Nyttige Ressurser
- Gruppediskusjon

## Først: liten ting

- Jeg eksperimenterer mye med R disse dager
  - Gøy for nerder heter det
- Lysbildene kommer gjerne til å utvikle seg litt over tid
- I tillegg kommer lysbildene som ligger på nett til å være litt annerledes.
  - De er mer vennlige å lese med tanke på eksamen (hvis det blir relevant)

## Bli *enda mer* kjent

- For de som ikke var med sist
- Jeg er Gard (26)
- Master i Statsvitenskap
- Faglig interesse for
  - Kvantitativ analyse
  - Political Data science
  - Kvinnelig Representasjon
  
## Forts. 

- Kvantitativ Tekstanalyse
- Valgsystemer
- Nasjonal Politikk i:
  - Japan
  - Taiwan
  - Sør-Korea
  - Israel
- Liker gaming, styrkeløfting og matlaging
  - Favoritt serie er Revolutionary Girl Utena
  - Favoritt album: A Night at the Opera av Queen


## Nå er det på tide med nok en klein icebreaker/bli kjent aktivitet

## Dagens lagaktivitet

- I grupper, gjør dere klar til å presentere laget deres
- Lag et lagnavn basert på fellesinteresse (gjerne med en morsom tvist)
- Presenter lagets gjennomsnittsalder
- Hva er den lengste og den korteste avstanden mellom to medlemmer i gruppa?
- Hvor mange år med utdanning har dere til sammen?

## <font color ="black"> Nå over til det faglige </font> {data-background-image="AndrepresImg/stortinget.jpg"}


## Formålet med disse seminarene

- Supplerer forelesningene
- Fokuset er stoffet, og læring av stoffet
- En lav-terskel arena for spørsmål
  - Det finnes ikke dumme spørsmål
- Mulighet for å lære av hverandre

## Hva skjer?

- Med i dag er det 11 faglige seminarer
- Samme dag, hver uke
- Følger forelesningene relativt nært
  - Tenk gjerne rundt dem i hht. pensum
- Kommer til å være nære oppgavene dere skal skrive

## Om Kvalifiseringsoppgavene

- 8 oppgaver fremover nå
- Fristen er to virkedager før seminarene
  - 48 timer før seminaret uten helg regnet med
- Leveres under oppgave mappen på Canvas
  - Oppgaven blir tilgjengelig etter seminaret
- Det kommer også en lengre 800 ords kvalifiseringsoppgave

## Om Kvalifiseringsoppgavene

- Skal ligge på rundt 250 ord hver
- Lista ligger ikke høyt på disse oppgavene
- Hovedfokuset er at dere skal lære av dem
- Og at de skal være et godt utgangspunkt for diskusjon i timene
- Legg likevel god innsats i dem
- Jeg gir bare individuell tilbakemelding hvis man får ikke godkjent
- Det kommer også en lengre kvalifiseringsoppgave på slutten
  - Mer info om det kommer senere
  
## Pirkegreier angående kvalifiseringsoppgavene

- Hei jeg heter Gard og elsker Computer Modern
- <p style="font-family:'Times New Roman'"> Hei jeg heter Gard og liker Times New Roman </p>
- <p style="font-family:'Calibri'"> Hei jeg heter Gard og hater Calibri </p>
- <p style="font-family:'Arial'"> Hei jeg heter Gard og hater Arial </p>


## Formelle krav

- Det kreves at dere får 4 av 8 oppgaver godkjent
  - Som sagt er ikke dette vanskelig
<br> <br>
- Oppmøte på minst 6 av 11 faglige seminarer
<br> <br>
- Godkjent lengre kvalifiseringsoppgave
<br> <br>
- Hvis dere ikke kan møte opp, si ifra
  - Meld til SV-info og til meg på gardod@student.sv.uio.no

## Formelle Krav

Prøv å ikke plag SV-info med mindre det trengs. Send bare e-post til dem hvis dere er i fare for å få ikke godkjent.

## Forventninger 

- I små grupper:
  - Hva forventer dere av meg?
  - Hva kan jeg gjøre for å møte deres forventninger?
  - Lag en liste over tre ting

## Forventninger

- Jeg er alltid tilgjengelig på mail
  - gardod@student.sv.uio.no
  - Jeg svarer som regel fort, særlig hvis det er på dagtid
- Still gjerne spørsmål hvis dere ser meg i gangene på SV
- Jeg kommer til å gjøre mitt beste for å svare spørsmål
  - Vær klar over at jeg kan henvise dere til andre
  - Men jeg gjør alltid mitt beste
  - Men husk, jeg er ingen ***absolutt*** autoritet
  
## Forventninger

- Hva jeg forventer av dere 
<br> <br>
- Si ifra når dere ikke kommer
<br> <br>
- Møt forberedt
<br> <br>
- Lever oppgavene innen tid
<br> <br>
- Vær aktive i diskusjoner

## Hva forventer dere av hverandre?

## Hvem å Kontakte?

- Generelt om faget:
  - Elin Allern - Emneansvarlig
- Noe til en spesifikk forelesning
  - Den relevante foreleseren - Guri Rosén, Elin Allern eller Raino Malnes
- Ang. Oppgavene 
  - Meg, enten student e-post eller gjennom canvas
- Melde fra om fravær
  - Meg (hovedsaklig) og SV-info

## Over til seminarene generelt

## Hvordan kommer seminarene til å se ut?

- Som nevnt ligger hovedfokuset på gruppediskusjoner
- Første time kommer vi til å diskutere oppgaven til seminaret
  - Mot slutten av timen tar jeg en oppsummerende tilbakemelding
  - I tillegg vil jeg si noe om hva jeg ville svart/hvordan jeg tolker oppgaven
  - Jeg vil muligens også bruke noen relevant eksempler og "forelese" litt om løsningene
  
## Hvordan kommer seminarene til å se ut?

- Andre time vil være dedikert til en diskusjonsaktivitet til den uka
- Formatet for indeling av grupper som skal diskutere vil variere
- Vi prøver å ta en oppsummerende samtale på slutten av hver time
- Jeg skal også prøve å være tilgjengelig mellom (og litt etter) timene, hvis dere har flere spørsmål.

## Kort om Ressurser

- Kildeføring
  - sokogskriv.no
- Pensum
  - Leganto på emnesiden: <font size="+2"> https://www.uio.no/studier/emner/sv/statsvitenskap/STV1010/h22/index.html </font>
- Generell litteratur kunnskap
  - Biblioteket
- Og selvfølgelig:
  - Ansatte
  - Hverandre


## Gruppediskusjon

- I grupper, diskuter de følgende spørsmålene
1. Hvorfor har du valgt å studere statsvitenskap? Hva motiverte fagvalget ditt?
2. Er du mest interessert i politikk internt i land eller internasjonale relasjoner (mellomland)? Eller virker begge deler like interessant?
3. Hva er det 21. århundres mest “brennbare spørsmål” som statsvitere burde utforske, etter ditt syn? Tenker du at de primært handler om politikk på nasjonalt eller internasjonalt nivå? Eller begge deler?

## Første Kvalifiseringsoppgave

Skru klokken 20 år tilbake, og anta at det er 2001, og at stortingsvalget nettopp har funnet sted. Valgdeltagelsen var 75,5%. Ved forrige stortingsvalg, i 1997, var valgdeltagelsen 78,3. En kommentator uttaler: "Vi ser at færre bruker stemmeretten nå enn tidligere i Norge. Valgdeltagelsen er nedadgående. Dette viser at folks misnøye med norske politikere i sin alminnelighet øker."

Hva slags slutninger trekker kommentatoren? Er det kommentatoren sier, velbegrunnet? Begrunn svarene dine kort.

Med valgdeltakelse menes andel av velgerne som avgir stemme ved valg. Du skal kun bruke informasjonen om valgdeltakelse i oppgaveteksten til å svare, ikke «fakta-sjekke» denne.

## Til neste gang!

- Husk å levere i tide!
- Ta med godt humør
- Takk for i dag!
