---
title: "Første Faglige Seminar"
author: "Gard Olav Dietrichson"
date: '`r format(Sys.time(), "%d-%m-%Y")`'
output:
  revealjs::revealjs_presentation:
    css: custom_style.css
    highlight: breezedark
    center: true
    code_folding: show
    transition: convex
    self_contained: false
    reveal_plugins: ["chalkboard", "notes"]
    reveal_options:
      slideNumber: true
css: custom_style.css
---

## Velkommen igjen!

## Plan for i dag

- Bli *enda mer* kjent
- Seminaropplegget fremover
  - Obligatoriske Krav
  - Kvalifiseringsoppgaver
  - Forventninger
- Nyttige Ressurser
- Gruppediskusjon


## Bli *enda mer* kjent

- For de som ikke var med sist
- Jeg er Gard (26)
- Master i Statsvitenskap
- Faglig interesse for
  - Kvantitativ analyse
  - Political Data science
  - Kvinnelig Representasjon
  
## Forts. 

- Kvantitativ Tekstanalyse
- Valgsystemer
- Nasjonal Politikk i:
  - Japan
  - Taiwan
  - Sør-Korea
  - Israel
- Liker gaming, styrkeløfting og matlaging
  - Favoritt serie er Revolutionary Girl Utena
  - Favoritt album: A Night at the Opera av Queen

## Nå er det på tide med nok en klein icebreaker/bli kjent aktivitet


## Nå over til det faglige [BILDE AV NOE HER]

## Formålet med disse seminarene

- Supplerer forelesningene
- Fokuset er stoffet, og læring av stoffet
- En lav-terskel arena for spørsmål
  - Det finnes ikke dumme spørsmål
- Mulighet for å lære av hverandre

## Hva skjer?

- Med i dag er det 11 faglige seminarer
- Samme dag, hver uke
- Følger forelesningene relativt nært
  - Tenk gjerne rundt dem i hht. pensum
- Kommer til å være nære oppgavene dere skal skrive

## Om Kvalifiseringsoppgavene

- 8 oppgaver fremover nå
- Fristen er to virkedager før seminarate
  - 48 timer før seminaret uten helg regnet med
- Leveres under oppgave mappen på Canvas
  - Oppgaven blir tilgjengelig etter seminaret
- Det kommer også en lengre 800 ords kvalifiseringsoppvae

## Om Kvalifiseringsoppgavene

- Skal ligge på rundt 250 ord hver
- Lista ligger ikke høyt på disse oppgavene
- Hovedfokuset er at dere skal lære av dem
- Og at de skal være et godt utgangspunkt for diskusjon i timene
- Legg likevel god innsats i dem
- Det kommer også en lengre kvalifiseringsoppgave på slutten
  - Mer info om det kommer senere
  
## Formelle krav

- Det kreves at dere får 4 av 8 oppgaver godkjent
  - Som sagt er ikke dette vanskelig
<br> <br>
- Oppmøte på minst 6 av 11 faglige seminarer
<br> <br>
- Godkjent lengre kvalifiseringsoppgave
<br> <br>
- Hvis dere ikke kan møte opp, si ifra
  - Meld til SV-info og til meg på gardod@student.sv.uio.no


