---
title: "Velkommen til Statsvitenskap"
author: "Gard Olav Dietrichson"
date: '`r format(Sys.time(), "%d-%m-%Y")`'
output: 
  beamer_presentation:
    theme: "AnnArbor"
    colortheme: "seahorse"
    fonttheme: "serif"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tinytex.verbose = TRUE)
```


## Plan for i dag! 

- Bli Kjent
  - Icebreaking
- Hva består livet av student som?
- Studieråd
  - Former for undervisning
  - Hvordan deltar man på forelesninger
  - Hva gjør man i seminarer?
- Pensum
  - Hvordan lese pensum
  - Hvordan lese forskningsartikler
  - Tips til hvordan lese og ta notater
- Kollokvier

## Bli Kjent


## Hvem er jeg?

- Gard (26)
- Fra Kolbotn, Akershus
- Master i Statsvitenskap
  - Skrevet om kvinners representasjon i MMR systemer, og bruk av kjønnskvoter
- Henger igjen for å søke på PhD i statsvitenskap
- Faglige Interesser:
  - Kvantitativ metode
  - Political Data Science
  - Kvinnelig representasjon
    - Deskriptiv og substansiell
  - Valgsystemer
    - Særlig MMR
  - Kvantitativ tekstanalyse
  
## Hvem er Jeg?

- Faglige Interesser forts:
  - Nasjonal politikk i:
    - Japan
    - Sør-Korea
    - Taiwan
    - Israel

## Hvem er Jeg?

- Bodde i Japan i et halvt år
  - Anbefaler alle å dra på utveksling
- Fritiden min bruker jeg på
  - Styrkeløfting (når jeg ikke er overarbeidet med Master)
  - Gaming
  - Matlaging
- Favoritt serie: Revolutionary Girl Utena
- Favoritt album: A Night at the Opera

## Men hvem er dere?

## Icebreaker


## Bli Kjent!

- Gå sammen med sidepersonen 
- Forbered dere på å introdusere sidepersonen til resten av gruppa
- Dette skal være med:
  - Navn
  - Alder
  - Hvor de er fra
  - Hvorfor valgte de statsvitenskap?
  - Favoritt tv-serie og/eller favoritt album
  
## Nå over til livet som student {data-background-image="FørstePresImg/emptywallet.jpg"}


## Hva består livet som student av?

- Hva forventer dere er annerledes?
- Diskuter i små grupper

## Først, litt småpirk

- Student | Ikke elev
- Universitet | Ikke Skole
- Virker veldig smålig (og det er det også), men skillet er viktig å holde i tankene når du ser forskjeller mellom denne institusjonen og tidligere erfaringer. 
- Dette universitetet er også litt særegent

## Som Student

- Er du din egen sjef og studiekoordinator
  - Du er ansvarlig for timeplanen
  - Du er ansvarlig for å være til stedet i tide
  - Du er ansvarlig for å være forberedt til eksamen
- Du har helt frihet for å organisere
- Men husk at frihet betyr ansvar

## Noen generelle råd

- Benytt deg av alt tilbud som du kan
  - Prioriter undervisning over alt
- Strukturer arbeidsdagen din
  - Prøv å være til stedet samme tid hver dag
  - Jeg brukte ikke en eneste helg på universitetet de første to årene
  - Tenk at det er en arbeidsdag
- Bruk mye tid på Campus!

## Undervisningsformer 

- Generelt sett blir dere kjent med to typer undervisning
- Forelesninger
- Seminarer
- Undervisning gjøres av et vidt spektrum av ansatte på UiO

## Forelesninger

- Forelesningene holdes av vitenskapelig ansatte
  - Emne-ansvarlig; Professorer, Førsteamanuensiser, Postdoktorer, PhD-stipendiater, og en og annen Universitetslektorer
- Formålet med forelesningene er å strukturere og kontekstualisere pensum
  - Men de hjelper også studentene til å finne ut av hva som bør vektlegges i pensum
- Forelesninger gir rask tilgang til nytt materiale
  - Ting som, konsepter, teorier, begrep og metoder forklares ofte
  
## Forelesninger

- Forelesningene kan variere voldsomt i henhold til digitale hjelpemidler
  - Disse midlene lastes ofte opp på nettsidene
    - Bruk dem aktivt i lesingen deres
- Husk også at de som underviser er ikke lærere
  - Stor sjanse for at dere får lære om dette personlig
    
## Hvordan bør du delta?

- Anbefalingen min er å delta i alle
- Når du er til stede, *vær til stede*
- Gjør alt mulig for å sikre at du er 100% klar til å følge med
- Vær kritisk til det du hører
  - Bruk pausene eller tiden etter til å stille spørsmål

## Notater

- Ta notater
  - Hvordan dette gjøres er vel mer en kunst enn en vitenskap
  - Jobb med å finne din metode for notatføring som gir mest utbytte
  - Husk at notater føres ikke nødvendigvis for at du skal lese dem i fremtiden
  - *ikke* skriv ned alt foreleser sier...
- Sjekk gjerne heftet som Elin har lagt ut for mer detaljerte råd

## Seminarer

- Grovt sett ser vi på tre type seminarer
  - Oppgaveskriving seminarer
  - Tekniske Seminarer
  - Undervisningsseminarer
- Disse er det nærmeste dere kommer en "klasse"
- Undervises som regel av Masterstudenter (eller tidligere Masterstudenter), og stipendiater

## Seminarer

- I seminarer er underviser mye mindre i fokus
- Studentene skal være i fokus, og det forventes aktiv deltakelse
- Seminarene er aktive læringsarenaer, der du kan lære av medstudenter og av seminarleder
- Fordrer selvfølgelig deltakelse, desto færre som deltar, desto mindre utbytte

## Pensum 


## Pensum

- Mange vil oppleve et brutalt møte med pensum på statsvitenskap
- Flere typer læringsmateriale blir som regel satt som pensum

## Pensum typer

- Læringsbøker
  - Den "vennligste" formen
  - Kompakt, oversiktlig, strukturert. 
  - Summerer ofte mye av forskningen gjort på et felt
  - Setter forskningen i en kontekst
- Literature Reviews
  - Oversiktsartikler, summerer opp sidene i en debatt
- Originale forskningsartikler
  - Ny forskning som belyser visse problemstillinger. 
  
## Hvordan lese faglig pensum

- Det er tunge saker
  - Vær klar for å måtte lese det flere ganger
- Lesing er en ferdighet, tren den!
- To former for lesing:
  - Lesing til eksamen
    - Det vanskeligste, uvisst hva du skal ta med deg
  - Lesing til en oppgave
    - Lettere, da vet du nok hva du leter etter

## Faglige Artikler

- Innledning - Rettferdiggjøring, kontekstualisering, literatur gjennomgang, Forskningsspørsmålet
- Teori - Teoretisk rammeverk, noe som forklarer verden, og setter forventninger
- Metode - Hvordan svare på spørsmålet, gjennom teorien
- Analyse - Resultatene av metoden
- Diskusjon - Hva betyr resultatene?
- Konklusjon - Det du skal ta med deg
- **Det du skal hente ut av oppgaven varierer med emne**

## Notater

- Ta noen form for notater
  - Igjen, det du skriver er ikke alltid viktig
- Planlegg intervaller
  - 30 min lesing, 5 min pause f.eks. 

## Til sist: Kollokvier



## Kollokvier 

- Den eminente professor Allern beskriver dem som
  - "Et frivilig must"
- En uvurdelig ressurs for alle
  - Uansett nivå
- Bruk de gjerne til å gå gjennom pensum
  - Lær av andre
  - Lær andre
- Fint å ha en fast gruppe og en fast tid

## Avslutningsvis

- Har dere noen flere spørsmål rundt det vi har snakket om?


## Dette var alt for i dag

- Husk at neste gang er obligatorisk oppmøte
- Ta med godt humør!
